package org.acme;

import com.microsoft.playwright.*;
import com.microsoft.playwright.options.AriaRole;
import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.*;

import static org.assertj.core.api.Assertions.assertThat;

/* The app must be running for these tests to pass */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@QuarkusTest
public class EndToEndTest {

    public static final String BASE_URL = "http://localhost:8080";
    public static final String DOCUMENT_GENERATION_ENDPOINT = "/newInvoice.xhtml";

    private Playwright playwright;
    private static Browser browser;
    private BrowserContext context;
    private Page page;

    @BeforeAll
    void launchBrowser() {
        playwright = Playwright.create();
        browser = playwright.firefox().launch();
    }

    @AfterAll
    void closeBrowser() {
        if (browser != null) {
            browser.close();
        }
        if (playwright != null) {
            playwright.close();
        }
    }

    @BeforeEach
    void createContextAndPage() {
        context = browser.newContext();
        page = context.newPage();
    }

    @AfterEach
    void closeContext() {
        if (context != null) {
            context.close();
        }
    }
/**********************************************************
Code generated by Playwright, after these commands:
 npx playwright codegen http://localhost:8080/index.xhtml

@UsePlaywright
public class TestExample {
    @Test
    void test(Page page) {
        page.navigate("http://localhost:8080/index.xhtml");
        page.getByPlaceholder("Invoice Number").click();
        page.getByPlaceholder("Invoice Number").fill("2");
        page.getByPlaceholder("Invoice Date").click();
        page.getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("18")).click();
        page.getByPlaceholder("Customer Name").click();
        page.getByPlaceholder("Customer Name").fill("Jose");
        page.getByPlaceholder("Customer Name").press("Tab");
        page.getByPlaceholder("Amount").fill("250.45");
        page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Submit")).click();
    }
}
   /*********************************************************/

    @Test
    void endToEndTest() throws InterruptedException {
        page.navigate(BASE_URL + DOCUMENT_GENERATION_ENDPOINT);
        System.out.println("============== Page title: " + page.title());
//        var pageTree = page.content();
//        System.out.println("Page Tree: " + pageTree);

        // Fill out the form

//        var input = page.waitForSelector("#invoiceNumber");     // It does NOT work
        page.getByPlaceholder("Invoice Number").click();
        page.getByPlaceholder("Invoice Number").fill("2");
        page.getByPlaceholder("Invoice Date").click();
        page.getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("18")).click();
        page.getByPlaceholder("Customer Name").click();
        page.getByPlaceholder("Customer Name").fill("Jose");
        page.getByPlaceholder("Customer Name").press("Tab");
        page.getByPlaceholder("Amount").fill("250.45");

        // Submit the form
        page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Submit")).click();

        // Wait for the result to appear
//        page.wait(3000L);  // waitForSelector("#result");
//        Locator messages = page.locator("form div[id='messages']");

//        var messageText = messages.textContent();

        // Check the result
        assertThat("DOCUMENT GENERATION").isEqualTo(page.title());
//        assertThat(messageText, startsWith("Success"));   // Hamcrest assertion
//        assertThat(messageText).startsWith("Success - Invoice submitted successfully with these data: "); // Assertj assertion
//        assertThat(messageText).contains("2", "2023-09-04", "Jose", "100.00");

    }






}





















